Application has thrown an uncaught exception and is terminated:
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at I:\Git\Node.js\practica7\SegundoSitioWebMatrix\server.js:29:30
    at Array.forEach (native)
    at Server.<anonymous> (I:\Git\Node.js\practica7\SegundoSitioWebMatrix\server.js:24:21)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
